### ISSUE TITLE
Headless mode not working with jsdom ^12.2.0

### ISSUE THREAD

**Issue by mfont-gh** [FirebaseExtended/firepad#332]
Hi 

I'm trying Firepad headless mode and I got some errors calling `headless.getHtml()`

firepad: 1.5.3
jsdom: ^12.2.0

### Test case

```js
var Firepad  = require('firepad');
var firebase = require('firebase');

// Initialize Firebase.
var config = {
       apiKey: "your api key",
       authDomain: "your domain",
       databaseURL: "your database url",
       ref: "your ref" 
     };
firebase.initializeApp(config);
var rootRef = firebase.database().ref();
var firepadRef = rootRef.child(config.ref);
var headless = new Firepad.Headless(firepadRef);
headless.getText(function(text) {
  console.log("Contents of firepad retrieved: " + text);
});
headless.getHtml(function(text) {
  console.log("Contents of firepad retrieved: " + text);
});
```

### Steps to reproduce

Execute the previous code snippet

### Expected behavior
Get the HTML of the firepad document

### Actual behavior

I got this error 

```bash
node_modules/firepad/dist/firepad.min.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e,r){"undefined"!=typeof module&&module.exports?module.exports=e():"function"==typeof r.define&&r.define.amd?define(e):r.Firepad=e()}(0,function(){var t;return(t=t||{}).utils={},t.utils.makeEventEmitter=function(t,e){t.prototype.allowedEvents_=e,t.prototype.on=function(t,e,r){this.validateEventType_(t),this.eventListeners_=this.eventListeners_||{},this.eventListeners_[t]=this.eventListeners_[t]||[],this.eventListeners_[t].push({callback:e,context:r})},t.prototype.off=function(t,e){this.validateEventType_(t),this.eventListeners_=this.eventListeners_||{};for(var r=this.eventListeners_[t]||[],n=0;n<r.length;n++)if(r[n].callback===e)return void r.splice(n,1)},t.prototype.trigger=function(t){this.eventListeners_=this.eventListeners_||{};for(var e=this.eventListeners_[t]||[],r=0;r<e.length;r++)e[r].callback.apply(e[r].context,Array.prototype.slice.call(arguments,1

TypeError: require(...).env is not a function
    at o.initializeFakeDom (/home/mfont/dev/code_tests/firepad/node_modules/firepad/dist/firepad.min.js:1:82851)
    at o.getHtml (/home/mfont/dev/code_tests/firepad/node_modules/firepad/dist/firepad.min.js:1:83100)
    at Object.<anonymous> (/home/mfont/dev/code_tests/firepad/f.js:18:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

```
In function Headless.prototype.initializeFakeDom, jsdom is used and seems that have a new API. One possible solution could be replace 

```js
require('jsdom').env('<head></head><body></body>', function(err, window) {
}
``` 

for this

```js
var jsdom = require('jsdom');
const { JSDOM } = jsdom;
const { window } = new JSDOM();
```
Thanks

**Comment by mikelehen** [comment]
Thanks for the report.  Any interest in sending a PR with the fix? 😄

**Comment by mfont-gh** [comment]
I'm not used to do a PR, but I'll try it ;)

**Comment by samtstern** [comment]
Fixed by #334

**Comment by JoseVigil** [comment]
@mikelehen appleciate if you can deploy the fix, thanks.

**Comment by mikelehen** [comment]
I deployed 1.5.4 over the weekend. Can you give it a try?

**Comment by JoseVigil** [comment]
@mikelehen the deploy worked like charm, _getHtml_ is now working correctly. Appreciate.
