### ISSUE TITLE
Multiple Files

### ISSUE THREAD

**Issue by SimonKlausLudwig** [FirebaseExtended/firepad#340]
Is it possible to create multiple pads Like you did it here https://demo.firepad.io/#sONrYc4axb ?

**Comment by mikelehen** [comment]
The source for firepad-demo is here: https://github.com/firebaseextended/firepad-demo

**Comment by michelson** [comment]
it seems that the demo is not working:

I see in  console 

```
errors.ts:101 Uncaught FirebaseError: Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app).
    at initializeApp (https://www.gstatic.com/firebasejs/7.6.2/firebase.js:1:72088)
    at Object.Os.initializeApp (https://www.gstatic.com/firebasejs/7.6.2/firebase.js:1:75732)
    at joinFirepadForHash (https://demo.firepad.io/demo.js:13:12)
    at dispatch (https://www.firepad.io/js/jquery-1.9.1.min.js:3:28337)
    at v.handle (https://www.firepad.io/js/jquery-1.9.1.min.js:3:25042)
```
